fixtures:
  repositories:
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    ssh: "https://github.com/saz/puppet-ssh.git"
  symlinks:
    keymaster: "#{source_dir}"
